### ISSUE TITLE
add bitcoinbasicspodcast.com > Bitcoin Podcasts

### ISSUE THREAD

**Issue by proofofgeek** [jlopp/lopp.net#582]
The Bitcoin Basics Podcast translates technical & economical concepts & key fundamentals of Bitcoin for the beginner & everyday person. We try to make Bitcoin accessible. Not buzzwords but the basics.

Gordon (co-host of bitcoinbasicspodcast.com).

**Comment by jlopp** [comment]
I'm getting a connection timeout when trying to load https://bitcoinbasicspodcast.com/

Note that all links from my web site get monitored automatically and those that are unreliable get removed. I recommend signing up for a free account at https://uptimerobot.com so that you will be automatically alerted if your site becomes unreachable.

**Comment by proofofgeek** [comment]
Resolved. We were having "technical difficulties" with moving servers last weekend. All good now. Thanks!
