### ISSUE TITLE
Translate Bitcoin Explained to Spanish

### ISSUE THREAD

**Issue by pmartincalvo** [jlopp/lopp.net#942]
Hi Jameson. I think this page is great: https://www.lopp.net/bitcoin-information/bitcoin-explained.html

I would like to share it with Spanish speakers, so I'm offering myself to translate it.

The only thing I need from you is guidance on how should we proceed. I see that the texts are hardcoded in the HTML. Should make another copy of the HTML? Do you perhaps have the same text stored in a more friendly format like markdown somewhere else? I'll wait for your feedback on this.

**Comment by jlopp** [comment]
Hm, I don't really want to go down a rabbit hole of maintaining a bunch of translations, because there are usually easier workarounds.

For example, you could just link to a google translated version at https://www-lopp-net.translate.goog/bitcoin-information/bitcoin-explained.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=en&_x_tr_pto=wapp

Otherwise, I'd suggest that you just save the entire page and files, translate the appropriate HTML, and host the whole package yourself.
